### ISSUE TITLE
Push to the official train craft repo

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/TrainCraft-1.8.9#1]
Push to the official train craft repo at https://github.com/Mrbrutal/Traincraft-5
- If it has a (better?) FOSS license

OR
- Use a different name

**Comment by NitroxydeX** [comment]
Just letting you know what I think about this:

If 1. doesn't happen then 2. is the only way to go. The License of Original Traincraft is not that good and deters many developers to work on it.

So if MrBrutal won't change the license then Traincraft is dead and option 2 would be the best.

**Comment by AlexIIL** [comment]
That sums up my train of thought pretty well :). I would like to try talking to him though and see what he thinks before jumping to a conclusion though.

**Comment by lehjr** [comment]
Honestly, I would say "absurd" is a better label for the current license. I do wish you luck with it though.

**Comment by NitroxydeX** [comment]
That sounds like music in my ears @AlexIIL. This makes me crying. _sniffle_
We get a port (or new mod). This is so beautiful!

@lehjr good description :D 

I think he won't change the license but lets see.

**Comment by Tar-Gilkaltar** [comment]
A new name may be the best way to start your development. On the other hand you will need new models of trains but it is many model creators. :)

I would like to see a more coherent system of rails. As an example railroad siding vs. railway cross P....

**Comment by AlexIIL** [comment]
@Tar-Gilkaltar Because of the differences between 1.6.4 and 1.8.9 all models would need redoing anyway, so it makes more sense to just create new ones rather than rework the old ones.

As for tracks I think you will like the way that I will do points and crossings...

**Comment by Tar-Gilkaltar** [comment]
@AlexIIL yeah, I am looking forward to new system of tracks.

The new name may ve something like: newtrain, minetrain, minelocomotion, lococraft... 

It would be nice to allow the addition of custom models like in Flan's Mod. :)

**Comment by AlexIIL** [comment]
This issue was moved to AlexIIL/TrainCraft-Ideas#3

**Comment by AlexIIL** [comment]
Not possible as the original TrainCraft has assets that cannot be licensed in another way.
