### ISSUE TITLE
Perhaps there shouldn't be an 8 wide curved track...

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/TrainCraft-1.8.9#13]
At what point is it just tooo big?

**Comment by chardo440** [comment]
4 or 6 is probably the max I'd think. Anything is better than vanilla tracks trying to make a curve.

**Comment by NitroxydeX** [comment]
You have a 45° curve 8 that's way too big. 

In Original Traincraft there was a 10x10 90° curve that was...uhm...I don't know. I think it was nice. So 8x8 shouldn't be too big as 90° curve.

So the 45° curved tracks are good, expect of the 8 wide.

90° curve should be: 4x4, 6x6, 8x8. Anything under 4x4 blocks is not realistic enough.

**Comment by AlexIIL** [comment]
The issue I have is that 8-wide curve is actually a 24x24 90 degree curve... which is ridiculous.

**Comment by NitroxydeX** [comment]
That's why I counted the curves in Blocks. 8x8 is 8x8 blocks. So 8 blocks forward and 8 blocks to the left/right

**Comment by AlexIIL** [comment]
In the next commit there will be a 5-wide one rather than an 8 wide one.

**Comment by AlexIIL** [comment]
(so you can have tracks that do this)
![2,3,4,5 curved tracks](https://cloud.githubusercontent.com/assets/3751138/12919437/f46ecd1e-cf3b-11e5-8155-d082ee21c49e.png)

**Comment by NitroxydeX** [comment]
Don't know what to think about the right one. This is really big.

**Comment by NitroxydeX** [comment]
Yeah, this seems to be okay.

If 8-wide is 24x24 then 5-wide is 15x15 in 90°? 

The invisible Blocks are development related I think?

**Comment by chardo440** [comment]
These look so good. I can't wait!

**Comment by AlexIIL** [comment]
8-wide was done in an older way, where the REAL width was 8 blocks. The new tracks have _shown_ widths of 2, 3, 4, 5 but have _hidden_ widths of 1.5, 2, 2.5 and 3. I'm also going to change the names from "width" to "radius" to better reflect what actually happens.

The invisible blocks are "pointers" that point to the ACTUAL track block fro the path. This is to make searching for a track path quicker, as the train only needs to search the 27 blocks in a 3x3x3, rather than all possible places that a curved track could originate from. I will make the invisible blocks have the proper bounding box soon, and make them break when the origin block is broken when I get the track pointers placing down correctly.

**Comment by NitroxydeX** [comment]
So that means that these block are likely not there in the final stage of the tracks or just that small that you didn't notice them and can't run against them?

**Comment by AlexIIL** [comment]
They should look like they are a part of the full curved track, and should have the correct bounding box for it too. They essentially form a "multi-block" for curved tracks that go over multiple tracks, and will be in the final release.

**Comment by NitroxydeX** [comment]
I think I don't get you right there without a picture reference :D

**Comment by AlexIIL** [comment]
Fair enough :P
It will look like TrainCraft in 1.6.4:
![screenshot from 2016-02-09 16 05 11](https://cloud.githubusercontent.com/assets/3751138/12921842/fef24b7a-cf46-11e5-8d7c-da4c1e83822d.png)

**Comment by NitroxydeX** [comment]
Ahh. Never really looked at the curves of Traincraft. The update came really late when 1.7.10 was already too big. ^^

But to sum this up as I said: You can't run against them ^^

**Comment by AlexIIL** [comment]
The not being able to run up against them is a bug :)

**Comment by AlexIIL** [comment]
Here is a comparison of 45-degree verses the new 90-degree turns. Much better :)
![screenshot from 2016-02-09 16 48 11](https://cloud.githubusercontent.com/assets/3751138/12923267/fde018ec-cf4c-11e5-8bfe-a067ddcac679.png)

(also the next commit is breaking, but it should be the last one that removes your blocks)

**Comment by chardo440** [comment]
Yeah I'd say that looks much better!  Those are good sized curves too.

**Comment by NitroxydeX** [comment]
Pretty nice ones. I think you can't really compare them. 45° turns are more to work with the diagonal tracks rather then making a turn. 

Something like this:
![2016-02-09_18 41 36](https://cloud.githubusercontent.com/assets/9305576/12925067/d6dc21f4-cf5c-11e5-898c-9bb5f58ff974.png)

And about running against them: This is when it will looks like in Traincraft. You because it's not a block anymore ^^

**Comment by Larky2k** [comment]
the size of the turn would depend on the size of the locomotive. So bigger turns will make things look smoother going around corners and allow bigger locomotives. 

Also something seems off with the size comparison.

**Comment by AlexIIL** [comment]
The left of the side comparison is made up of 2 separate 45-degree turns, but the ones on right are just a single 90-degree turn.

**Comment by Larky2k** [comment]
ah that explains it. :)

**Comment by AlexIIL** [comment]
Thanks for all the feedback :)
