### ISSUE TITLE
Models of curved tracks

### ISSUE THREAD

**Issue by AlexIIL** [AlexIIL/TrainCraft-1.8.9#6]
An automatic generator that can provide:
- [x] Sleepers curving round
- [x] Rails curving round
- [x] Correct paths

**Comment by AlexIIL** [comment]
Technically implemented but the curved paths are still wrong.

**Comment by NitroxydeX** [comment]
It's a bit early but I think questions and feedback is a good thing. I grabbed the latest commit to look at curved tracks.

Maybe this is not final or maybe it is but I think putting a diagonal track between two curves is not the best way. It looks in my opinion a little bit weird if there is a little kink in the curve. See attached photos. 

Maybe this is only the way for 45° curves and you implement 90° curves too. Then it's okay.

![2016-02-08_22 00 04](https://cloud.githubusercontent.com/assets/9305576/12899110/2cef1d60-ceb0-11e5-955d-818134046d40.png)
![2016-02-08_22 00 12](https://cloud.githubusercontent.com/assets/9305576/12899111/2cfb508a-ceb0-11e5-99a2-b92b257b2ee2.png)
![2016-02-08_22 03 59](https://cloud.githubusercontent.com/assets/9305576/12899112/2d0d5122-ceb0-11e5-87ca-1e46ac6d66b5.png)

**Comment by AlexIIL** [comment]
Yeah, that was the first thing I noticed when joining them :) (its was mathematically horrible to try and get 45 degree curves to work at all, so I don't want to waste another week modifying them).

Adding 90 degree turns is the easiest way to fix this though, so I might implement it tomorrow.

**Comment by AlexIIL** [comment]
(The commit you used is AFTER I fixed curved tracks BTW). I'm continuing 90 degree curves in #12.

**Comment by NitroxydeX** [comment]
I think there is still something wrong with the paths. Train always derail at the second curve. No matter how long the diagonal track is between them

![2016-02-09_15 14 34](https://cloud.githubusercontent.com/assets/9305576/12918592/2dc25460-cf40-11e5-9a1c-53480c002f61.png)

Even if you start it on the diagonal track it directly derails on the curve.

![2016-02-09_15 18 33](https://cloud.githubusercontent.com/assets/9305576/12918679/7d93aa0c-cf40-11e5-98b8-a50f80ddab8d.png)

And there is a problem with the curved 8 track.

http://pastebin.com/gBRpsHm3

It's placed after reloading but Minecraft crashs on placement

**Comment by AlexIIL** [comment]
I'm just about to push a breaking commit (that breaks the way curved tracks work), but it does also fix the 8-wide curves crashing
